# <font face="gotham" color="purple"> Basic Operation </font>

In [9]:
X = 34
Y = 3

In [10]:
X + Y
X - Y
X * Y
X ^ Y
X %% Y
class(X)

[1] 37

[1] 31

[1] 102

[1] 39304

[1] 1

[1] "numeric"

In [16]:
A = 'Helsinki'
B = 'Warsaw'
C = 'Stockholm'
D = 'Budapest'

In [12]:
class(A)

[1] "character"

In [14]:
v <- c(3, 6, 9, 15)
w <- c(4, 6, 8, 12)

In [15]:
v + w

[1]  7 12 17 27

In [17]:
cities <- c(A, B, C, D)

In [18]:
cities

[1] "Helsinki"  "Warsaw"    "Stockholm" "Budapest"

In [20]:
names(w) <- c(A, B, C, D)

In [21]:
w

Helsinki    Warsaw Stockholm  Budapest 
        4         6         8        12

In [22]:
w[3]

Stockholm 
        8

In [23]:
w['Stockholm']

Stockholm 
        8

In [24]:
w[c(2, 3)]

Warsaw Stockholm 
        6         8

In [25]:
w[c(2:4)]

Warsaw Stockholm  Budapest 
        6         8        12

In [26]:
mean(w)

[1] 7.5

In [27]:
w > 7

Helsinki    Warsaw Stockholm  Budapest 
    FALSE     FALSE      TRUE      TRUE

In [28]:
w[w>7]

Stockholm  Budapest 
        8        12

In [31]:
matrix(1:12, byrow=TRUE, nrow=3)

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [32]:
matrix(1:12, byrow=FALSE, nrow=3)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [36]:
v <- c(3, 6, 9, 15)
w <- c(4, 6, 8, 12)
v_w <- c(v, w)

In [37]:
v_w

[1]  3  6  9 15  4  6  8 12

In [39]:
v_w_mat <- matrix(v_w, byrow=TRUE, nrow=4)

In [40]:
v_w_mat

[,1] [,2]
[1,] 3     6  
[2,] 9    15  
[3,] 4     6  
[4,] 8    12

## Naming Matrix

In [41]:
mat_A <- matrix(1:9, byrow=TRUE, nrow=3)
print(mat_A)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [42]:
rownames(mat_A) <- c('Row 1', 'Row 2', 'Row 3')
colnames(mat_A) <- c('Col 1', 'Col 2', 'Col 3')

In [43]:
print(mat_A)

      Col 1 Col 2 Col 3
Row 1     1     2     3
Row 2     4     5     6
Row 3     7     8     9


In [44]:
rowSums(mat_A)

Row 1 Row 2 Row 3 
    6    15    24

In [46]:
colSums(mat_A)

Col 1 Col 2 Col 3 
   12    15    18

In [52]:
mat_B = matrix(2:10, byrow = FALSE, nrow = 3)
mat_B

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [53]:
mat_A + mat_B

Col 1 Col 2 Col 3
Row 1  3     7    11   
Row 2  7    11    15   
Row 3 11    15    19

In [64]:
mat_A * mat_B

Col 1 Col 2 Col 3
Row 1  2    10    24   
Row 2 12    30    54   
Row 3 28    56    90

In [65]:
mat_A / mat_B

Col 1    Col 2     Col 3    
Row 1 0.500000 0.4000000 0.3750000
Row 2 1.333333 0.8333333 0.6666667
Row 3 1.750000 1.1428571 0.9000000

In [ ]:
mat_A %*% mat_B # matrix multiplication

In [55]:
cbind(mat_A, mat_B)

Col 1 Col 2 Col 3       
Row 1 1     2     3     2 5  8
Row 2 4     5     6     3 6  9
Row 3 7     8     9     4 7 10

In [57]:
rbind(mat_A, mat_B)

Col 1 Col 2 Col 3
Row 1 1     2      3   
Row 2 4     5      6   
Row 3 7     8      9   
      2     5      8   
      3     6      9   
      4     7     10

## Check Workspace

In [56]:
ls()

[1] "A"        "B"        "C"        "cities"   "D"        "mat_A"   
 [7] "mat_B"    "v"        "v_w"      "v_w_mat"  "vector_a" "vector_b"
[13] "w"        "X"        "Y"

# Select Matrix Element

In [58]:
mat_C = matrix(1:30, byrow=TRUE, nrow=5)

In [59]:
mat_C

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1    2    3    4    5    6  
[2,]  7    8    9   10   11   12  
[3,] 13   14   15   16   17   18  
[4,] 19   20   21   22   23   24  
[5,] 25   26   27   28   29   30

In [60]:
mat_C[,5]

[1]  5 11 17 23 29

In [61]:
mat_C[3,]

[1] 13 14 15 16 17 18

In [63]:
mat_C[2:5,4]

[1] 10 16 22 28